### PR TITLE
Fix Importer ;)

### PR DESCRIPTION
**Pull request by Nosxxx**
Hey, 
I fixed your importer ;)
May you try this ?

### CODE REVIEW

**Comment by greatman** [comment]
Hmm, thanks. Ill try it out when i'm done on my refactor things ;)

**Comment by Nosxxx** [comment]
Hm and ? I had no problems if use my fork for importing

**Comment by greatman** [comment]
Ill just need you to merge on top of master, did a couple of changes that fixes travis for PR's so it confirms it's fine.

**Comment by Nosxxx** [comment]
Travis does not work :S

**Comment by greatman** [comment]
One of the dependencies website is broken, hence breaking my build.

**Pull request closed without merging**
