### PR TITLE
Now the log command really works

### PR DESCRIPTION
**Pull request by Phoenix616**
Never checked if it really worked besides not throwing the exception until now... I should've done that sooner.

### CODE REVIEW

**Comment by greatman** [comment]
Ill just need you to merge on top of master, did a couple of changes that fixes travis for PR's so it confirms it's fine.

**Comment by Phoenix616** [comment]
Awesome! Done.

**Comment by Nosxxx** [comment]
May you will fork this ;) ?

**Comment by greatman** [comment]
@Nosxxx Will work on it tonight/tomorrow ;)

**Comment by greatman** [comment]
Manually pushed it (Squashed the commits): https://github.com/greatman/craftconomy3/commit/da5c844f79d60bc2e5940ec3c135708a0ac539b4

Thanks!

**Pull request closed without merging**
